version: '3'

services:
    app:
        build: ./
        container_name: app
        working_dir: /home/www
        ports:
            - '8000:8000'
        volumes:
            - ./:/home/www
    mysql:
        image: mysql:8.4.3
        container_name: mysql
        environment:
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        ports:
            - '3306:3306'